---
# Hadolint configuration
# https://github.com/hadolint/hadolint

failure-threshold: warning

ignored:
  # DL3018: Pin versions in apk add
  # - DL3018
  
  # DL3008: Pin versions in apt-get install
  # - DL3008

trustedRegistries:
  - docker.io
  - ghcr.io

label-schema:
  author: text
  maintainer: text
  version: semver
